version: 2

commands:


jobs:
  build:
    docker:
      - image: hseeberger/scala-sbt:17.0.0_1.5.5_3.1.0
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Compile samplescala dist package
          command: cat /dev/null | sbt clean update dist
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
  lint:
    requires:
      - build
    docker:
      - image: hseeberger/scala-sbt:17.0.0_1.5.5_3.1.0
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Run scalafmtCheck
          command: cat /dev/null | sbt scalafmtCheck
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"